services:
    node_api:
      build:
        context: ./node_api
      ports:
        - "3000:3000"
      container_name: node-app
      volumes:
        - ./node_api:/app
        - /app/node_modules
      command: node app.js
      networks:
        - app-network
           
    flask_api:
      build: 
        context: ./python_api
      container_name: python_api
      ports:
        - "5000:5000"
      volumes:
        - ./python_api:/app
      environment:
        - FLASK_ENV=development
        - DB_HOST=dbmysql
        - DB_PORT=3306
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_NAME=flaskdb
      command: python app.py
      depends_on:
        - dbmysql
      networks:
        - app-network
 
    dbmysql:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: flaskdb
      ports:
        - "3307:3306"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge