services:
    node_api:
      build:
        context: ./app_node
      ports:
        - "3000:3000"
      container_name: node-app
      volumes:
        - ./app_node:/app
         - /app/node_modules
      command: node app.js
      networks:
        - app-network
           
    flask_api:
      build: ./app_python
      container_name: python_app
      ports:
        - "5000:5000"
      volumes:
        - ./app_python:/app
      environment:
        - FLASK_ENV=development
        - DB_HOST=mysql_db
        - DB_PORT=3306
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_NAME=flaskdb
      command: python app.py
      depends_on:
        - mysql_db
      networks:
        - app-network
 
    mysql_db:
      image: mysql:8.0
      environment:
        MYSQL_USER: root
        MYSQL_HOST: mysql_db
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: flaskdb
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
volumes:
  mysql_data:


networks:
  app-network:
    driver: bridge